Controllers/API/InvitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FrameWorksExamen.Data;
using FrameWorksExamen.Models;
using Microsoft.AspNetCore.Authorization;

namespace FrameWorksExamen.Controllers.API
{
    [Route("api/[controller]")]
    [Authorize]
    [ApiController]
    public class InvitesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public InvitesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Invites
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Invite>>> GetInvite()
        {
          if (_context.Invite == null)
          {
              return NotFound();
          }
            return await _context.Invite.ToListAsync();
        }

        // GET: api/Invites/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Invite>> GetInvite(int id)
        {
          if (_context.Invite == null)
          {
              return NotFound();
          }
            var invite = await _context.Invite.FindAsync(id);

            if (invite == null)
            {
                return NotFound();
            }

            return invite;
        }

        // PUT: api/Invites/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutInvite(int id, Invite invite)
        {
            if (id != invite.Id)
            {
                return BadRequest();
            }

            _context.Entry(invite).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!InviteExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Invites
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Invite>> PostInvite(Invite invite)
        {
          if (_context.Invite == null)
          {
              return Problem("Entity set 'ApplicationDbContext.Invite'  is null.");
          }
            _context.Invite.Add(invite);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetInvite", new { id = invite.Id }, invite);
        }

        // DELETE: api/Invites/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteInvite(int id)
        {
            if (_context.Invite == null)
            {
                return NotFound();
            }
            var invite = await _context.Invite.FindAsync(id);
            if (invite == null)
            {
                return NotFound();
            }

            invite.deleted=true;
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool InviteExists(int id)
        {
            return (_context.Invite?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/CultureController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace FrameWorksExamen.Controllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public IActionResult SetCulture(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrameWorksExamen.Data;
using FrameWorksExamen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Localization;

namespace FrameWorksExamen.Controllers
{
    public class EventsController : ApplicationController
    {
        private readonly IStringLocalizer<EventsController> _localizer;

        public EventsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor, ILogger<ApplicationController> logger, IStringLocalizer<EventsController> localizer)
            : base(context, httpContextAccessor, logger)
        {
            _localizer = localizer;
        }

        // GET: Events
        public async Task<IActionResult> Index(string searchField, string searchField2)
        {
            var events = from e in _context.Event.Include(e=>e.Invited)
                         where (e.deleted.Equals(false))
                         orderby e.Name
                         select e;

            if (!string.IsNullOrEmpty(searchField))
            {
                events = from e in events
                         where e.Name.Contains(searchField)
                         orderby e.Name
                         select e;
            }
            if (!string.IsNullOrEmpty(searchField2))
            {
                events = from e in events
                         where e.Description.Contains(searchField2)
                         orderby e.Description
                         select e;
            }
            

            return _context.Event != null ?
                          View(await events.ToListAsync()) :
                          Problem("Entity set 'SL_Frameworks_FinalContext.Event'  is null.");

        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["Name"] = @event.Name;

            return View(@event);
        }
        [Authorize]
        // GET: Events/Create
        public IActionResult Create()
        {
            Event ev = new Event();
            ev.PeopleId = new List<int>();
            if(ev.Invited != null)
            {
                foreach(Person p in ev.Invited)
                {
                    ev.PeopleId.Add(p.Id);
                }
            }
            ViewData["PeopleId"] = new MultiSelectList(_context.Person.OrderBy(c => c.Name), "Id", "Name");
            
            
            return View(ev);
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Location,date,people,deleted,Invited,PeopleId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                if(@event.Invited == null)
                {
                    @event.Invited = new List<Person>();
                    foreach(int id in @event.PeopleId)
                    {
                        @event.Invited.Add(_context.Person.FirstOrDefault(p => p.Id == id));
                    }
                }
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PeopleId"] = new MultiSelectList(_context.Person.OrderBy(c => c.Name), "Id", "Name");
            return View(@event);
        }
        [Authorize]
        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["PeopleId"] = new MultiSelectList(_context.Person.OrderBy(c => c.Name), "Id", "Name");
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Location,date,people,deleted,Invited,PeopleId")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (@event.Invited == null)
                    {
                        @event.Invited = new List<Person>();
                        foreach (int i in @event.PeopleId)
                        {
                            @event.Invited.Add(_context.Person.FirstOrDefault(p => p.Id == i));
                        }
                    }
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }
        [Authorize]
        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Event == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Event'  is null.");
            }
            var @event = await _context.Event.FindAsync(id);
            if (@event != null)
            {
                
                @event.deleted = true;
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return (_context.Event?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/UsersController.cs
 using FrameWorksExamen.Data;
using FrameWorksExamen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using System.Data;

namespace FrameWorksExamen.Controllers
{
    [Authorize]
    public class UsersController : ApplicationController
    {
        private readonly IStringLocalizer<UsersController> _localizer;
        public UsersController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor, ILogger<ApplicationController> logger, IStringLocalizer<UsersController> localizer)
            : base(context, httpContextAccessor, logger)
        {
            _localizer = localizer;
        }
        public IActionResult Index(string userName, string firstName, string lastName, string email)
        {
            List<UserViewModel> vmUsers = new List<UserViewModel>();
            List<User> users = _context.Users
                                                .Where(u => u.UserName != "Dummy"
                                                        && (u.UserName.Contains(userName) || string.IsNullOrEmpty(userName))
                                                        && (u.FirstName.Contains(firstName) || string.IsNullOrEmpty(firstName))
                                                        && (u.LastName.Contains(lastName) || string.IsNullOrEmpty(lastName))
                                                        && (u.Email.Contains(email) || string.IsNullOrEmpty(email)))
                                                .ToList();
            foreach (User user in users)
            {
                vmUsers.Add(new UserViewModel
                {
                    
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    Roles = (from userRole in _context.UserRoles
                             where userRole.UserId == user.Id
                             orderby userRole.RoleId
                             select userRole.RoleId).ToList()
                });
            }
            ViewData["userName"] = userName;
            ViewData["firstName"] = firstName;
            ViewData["lastName"] = lastName;
            ViewData["email"] = email;
           
            return View(vmUsers);
        }

        public IActionResult Undelete(string userName)
        {
            User user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string userName)
        {
            User user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Roles(string userName)
        {

            User user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            RoleViewModel rvm = new RoleViewModel()
            {
                UserName = userName,
                Roles = (from userRole in _context.UserRoles
                         where userRole.UserId == user.Id
                         orderby userRole.RoleId
                         select userRole.RoleId).ToList()
            };

            ViewData["RoleIds"] = new MultiSelectList(_context.Roles.OrderBy(c => c.Name), "Id", "Name", rvm.Roles);
            return View(rvm);
        }

        [HttpPost]
        public IActionResult Roles([Bind("UserName,Roles")] RoleViewModel _model)
        {
            User user = _context.Users.FirstOrDefault(u => u.UserName == _model.UserName);
            List<IdentityUserRole<string>> userRoles = _context.UserRoles.Where(ur => ur.UserId == user.Id).ToList();
            foreach (IdentityUserRole<string> ur in userRoles)
            {
                _context.Remove(ur);
            }
            if (_model.Roles != null)
                foreach (string roleId in _model.Roles)
                    _context.UserRoles.Add(new IdentityUserRole<string>() { RoleId = roleId, UserId = user.Id });
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_CulturePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}
<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage"
          asp-controller="Culture"
          asp-action="SetCulture"
          asp-route-returnUrl="@returnUrl"
          method="post"
          class="form-horizontal nav-link text-dark"
          role="form">
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrameWorksExamen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrameWorksExamen.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FrameWorksExamen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Events" asp-action="Index">@Localizer["Events"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Invites" asp-action="Index">@Localizer["Invites"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="People" asp-action="Index">@Localizer["People"]</a>
                        </li>
                        
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">@Localizer["Users"]</a>
                        </li>
                        
                        
                        
                    </ul>
                    <partial name="_CulturePartial" />
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FrameWorksExamen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>